version: '3'

services:

    web:
        container_name: minical-web-1
        image: nginx:latest
        ports:
            - "8040:80"
        volumes:
            - "/Users/lil-pumpski/Downloads/MesaDigital/Reserved/PMS/docker/nginx.conf:/etc/nginx/conf.d/default.conf"
            - ../:/app
            - ../public:/app/public
        depends_on:
                - php
    php:
        container_name: minical-php-1
        build:
            context: .
            dockerfile: docker/PHP.Dockerfile
        volumes:
            - ../:/app
            - ../public:/app/public
        depends_on:
            - db
            - composer
        # Remove this line:
        # command: php artisan serve --host=0.0.0.0 --port=8080
        expose:
            - "9000"

    db:
        container_name: minical-db-1
        image: mariadb:latest
        environment:
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'minical_db'
        volumes:
            - ./mysql-config/my.cnf:/etc/mysql/my.cnf
            - mysqldata:/var/lib/mysql
        ports:
            - "3307:3306"  # Ensuring Laravel connects properly

    composer:
        container_name: minical-composer-1
        image: composer:latest
        command: ["sleep","infinity"]
        volumes:
            - ../:/app
            - ../public:/app/public
        working_dir: /app

    phpmyadmin:
        container_name: minical-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8888:80'
        environment:
            PMA_HOST: db
        depends_on:
            - db

volumes:
    mysqldata:
